package net.canvoki.vokibot

import android.content.Context
import android.content.Intent
import android.os.Build
import androidx.core.content.pm.ShortcutInfoCompat
import androidx.core.content.pm.ShortcutManagerCompat
import androidx.core.graphics.drawable.IconCompat
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.util.UUID

/**
 * Triggers on a shortcut icon in the home screen
 * @param id Autogenerated identifier of the shortcut
 * @param displayName Visible text of the shortcut
 */
@Serializable
@SerialName(ShortcutTrigger.TYPE)
data class ShortcutTrigger(
    override val id: String = "${UUID.randomUUID()}",
    val displayName: String,
) : Trigger() {
    companion object {
        const val TYPE = "trigger_shortcut"
        const val ICON = R.drawable.ic_shortcut

        val TYPE_INFO =
            EntityTypeInfo(
                typeKey = TYPE,
                entityClass = ShortcutTrigger::class,
                labelRes = R.string.triggerlist_option_shortcut,
                iconRes = ICON,
                editorFactory = { triggerId -> ShortcutTriggerEditor(triggerId) },
                deserializer = { jsonString -> fromJson(jsonString) },
                helpRes = R.string.trigger_shortcut_help,
            )

        const val MAX_SHORT_LABEL_LENGTH = 10
        const val MAX_LONG_LABEL_LENGTH = 25

        fun register() {
            StorableEntity.register(TYPE_INFO)
        }

        fun fromJson(jsonString: String): ShortcutTrigger = JsonConfig.decodeFromString(serializer(), jsonString)
    }

    override val type = TYPE
    override val iconRes get() = ICON
    override val title get() = displayName
    override val description get() = "ID: ${id.takeLast(6)}"

    // TODO: make this configurable
    val homeScreenIconRes get() = R.drawable.ic_brand

    override fun toJson(): String = JsonConfig.encodeToString(serializer(), this)

    fun isPinned(context: Context): Boolean {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) return false
        return ShortcutManagerCompat
            .getShortcuts(context, ShortcutManagerCompat.FLAG_MATCH_PINNED)
            .any { it.id == id }
    }

    private fun buildShortcutInfo(context: Context): ShortcutInfoCompat {
        val intent =
            Intent(context, ShortcutDispatchActivity::class.java).apply {
                action = ShortcutDispatchActivity.ACTION_TRIGGER
                putExtra(ShortcutDispatchActivity.EXTRA_TRIGGER_ID, id)
                flags = Intent.FLAG_ACTIVITY_NEW_TASK
            }
        val shortcut =
            ShortcutInfoCompat
                .Builder(context, id)
                .setShortLabel(title.take(MAX_SHORT_LABEL_LENGTH))
                .setLongLabel(title.take(MAX_LONG_LABEL_LENGTH))
                .setIcon(IconCompat.createWithResource(context, homeScreenIconRes))
                .setIntent(intent)
                .build()
        return shortcut
    }

    fun pin(context: Context) {
        val shortcut = buildShortcutInfo(context)
        ShortcutManagerCompat.requestPinShortcut(context, shortcut, null)
    }

    fun update(context: Context) {
        val shortcut = buildShortcutInfo(context)
        ShortcutManagerCompat.updateShortcuts(context, listOf(shortcut))
    }
}
