package net.canvoki.vokibot

import android.content.Context
import android.content.Intent
import android.os.Build
import androidx.core.content.pm.ShortcutInfoCompat
import androidx.core.content.pm.ShortcutManagerCompat
import androidx.core.graphics.drawable.IconCompat
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.util.UUID

/**
 * Triggers on a shortcut icon in the home screen
 * @param id Autogenerated identifier of the shortcut
 * @param displayName Visible text of the shortcut
 */
@Serializable
data class ShortcutTrigger(
    override val id: String = "${UUID.randomUUID()}",
    val displayName: String,
) : Trigger() {
    companion object : EntityMetadata {
        const val MAX_SHORT_LABEL_LENGTH = 10
        const val MAX_LONG_LABEL_LENGTH = 25

        override val typeKey = "trigger_shortcut"
        override val entityClass = ShortcutTrigger::class
        override val labelRes = R.string.triggerlist_option_shortcut
        override val iconRes = R.drawable.ic_shortcut
        override val editorFactory = { triggerId: String? -> ShortcutTriggerEditor(triggerId) }
        override val deserializer = { jsonString: String -> fromJson(jsonString) }
        override val helpRes = R.string.trigger_shortcut_help

        fun register() = StorableEntity.register(this)

        fun fromJson(jsonString: String): ShortcutTrigger = JsonConfig.decodeFromString(serializer(), jsonString)

        fun fromExistingShortcut(
            context: Context,
            id: String,
        ): ShortcutTrigger? {
            if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) return null
            val info =
                ShortcutManagerCompat
                    .getShortcuts(context, ShortcutManagerCompat.FLAG_MATCH_PINNED)
                    .firstOrNull { it.id == id }
                    ?: return null
            return ShortcutTrigger(
                id = id,
                displayName =
                    info.longLabel?.toString()
                        ?: info.shortLabel.toString(),
            )
        }

        fun idFromUid(id: String) = id
    }

    override val type = ShortcutTrigger.typeKey
    override val iconRes get() = ShortcutTrigger.iconRes

    override fun getTitle(context: Context): String = displayName

    override val description get() = "ID: ${id.takeLast(6)}"

    // TODO: make this configurable
    val homeScreenIconRes get() = R.drawable.ic_brand

    override fun toJson(): String = JsonConfig.encodeToString(serializer(), this)

    fun isPinned(context: Context): Boolean {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.R) return false
        return ShortcutManagerCompat
            .getShortcuts(context, ShortcutManagerCompat.FLAG_MATCH_PINNED)
            .any { it.id == id }
    }

    private fun buildShortcutInfo(context: Context): ShortcutInfoCompat {
        val intent =
            Intent(context, ShortcutDispatchActivity::class.java).apply {
                action = ShortcutDispatchActivity.ACTION_TRIGGER
                putExtra(ShortcutDispatchActivity.EXTRA_TRIGGER_ID, id)
                flags = Intent.FLAG_ACTIVITY_NEW_TASK
            }
        val title = getTitle(context)
        val shortcut =
            ShortcutInfoCompat
                .Builder(context, id)
                .setShortLabel(title.take(MAX_SHORT_LABEL_LENGTH))
                .setLongLabel(title.take(MAX_LONG_LABEL_LENGTH))
                .setIcon(IconCompat.createWithResource(context, homeScreenIconRes))
                .setIntent(intent)
                .build()
        return shortcut
    }

    fun pin(context: Context) {
        val shortcut = buildShortcutInfo(context)
        ShortcutManagerCompat.requestPinShortcut(context, shortcut, null)
    }

    fun update(context: Context) {
        val shortcut = buildShortcutInfo(context)
        ShortcutManagerCompat.updateShortcuts(context, listOf(shortcut))
    }
}
